OPC7/force-app/main/default/objects/Livraison__c/Livraison__c.object-meta.xml
<CustomObject>
    <label>Livraison</label>
    <nameField>
        <displayFormat>Livraison-{0000}</displayFormat>
        <label>Livraison Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Livraisons</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

OPC7/force-app/main/default/objects/Livraison__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Livraisons</relationshipLabel>
    <relationshipName>Livraisons</relationshipName>
    <type>Lookup</type>
</CustomField>

OPC7/force-app/main/default/objects/Livraison__c/fields/Transporteur__c.field-meta.xml
<CustomField>
    <fullName>Transporteur__c</fullName>
    <label>Transporteur</label>
    <referenceTo>Transporteur__c</referenceTo>
    <relationshipLabel>Livraisons</relationshipLabel>
    <relationshipName>Livraisons</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

OPC7/force-app/main/default/classes/LivraisonController.cls
public with sharing class LivraisonController {

    // Méthode pour créer une livraison avec le transporteur le moins cher pour une commande donnée
      @AuraEnabled
        public static void createLivraisonWithCheapestTransporter(Order order) {
            Transporteur__c cheapestTransporter = TransporterSelector.calculateCheapestTransporter(order);
            
            if (cheapestTransporter != null) {
                Livraison__c newLivraison = new Livraison__c();
                newLivraison.Order__c = order.Id;
                newLivraison.Transporteur__c = cheapestTransporter.Id;
                newLivraison.Account__c = order.AccountId;
                newLiveraison.Status__c = 'En cours';

                insert newLivraison;
            }

        }
        // Méthode pour créer une livraison avec le transporteur le plus rapide pour une commande donnée
        @AuraEnabled
        public static void createLivraisonWithFastestTransporter(Order order) {
            Transporteur__c fastestTransporter = TransporterSelector.calculateFastestTransporter(order);
            
            if (fastestTransporter != null) {
                Livraison__c newLivraison = new Livraison__c();
                newLivraison.Order__c = order.Id;
                newLivraison.Transporteur__c = fastestTransporter.Id;
                newLivraison.Account__c = order.AccountId;                
                newLiveraison.Status__c = 'En cours';

                insert newLivraison;
            }
        }
    // Méthode pour créer une livraison avec un transporteur sélectionné par l'utilisateur pour une commande donnée
        @AuraEnabled
        public static Boolean createLivraisonWithSelectedTransporter(String orderId, String selectedTransporterId) {
          return false;
        }
    
}